### ISSUE TITLE
Custom montage

### ISSUE THREAD

**Issue by sdascoli** [zhangzihan-is-good/Chisco#3]
Thanks for this great dataset!
It looks like you are using a custom montage, but I couldn't find the file `montage.csv` anywhere in the repo or OpenNeuro.
Could you upload it?
Many thanks!

https://github.com/zhangzihan-is-good/Chisco/blob/bb2cf1e47c48dc7c3e2ce2db49457bfb543353df/preprocessing.py#L68

**Comment by zhangzihan-is-good** [comment]
We appreciate your interest in our research. As the EEG cap manufacturer did not provide an official montage file, we have developed a custom montage, which has been added to the repository.

**Comment by sdascoli** [comment]
Perfect, thanks a lot!
